### ISSUE TITLE
Compilation error: `fatal error: rpc/types.h: No such file or directory`.

### ISSUE THREAD

**Issue by dreirund** [iknowjason/voiphopper#3]
I just wanted to compile your software "voiphopper" [1], version version 2.04 [2].

Build fails for me with  
`main.c:30:10: fatal error: rpc/types.h: No such file or directory`:  
```
Making all in src
make[1]: Entering directory '/tmp/makepkg/build/voiphopper/src/voiphopper-2.04/src'
gcc -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"voiphopper\" -DVERSION=\"2.04\" -I.     -march=native -mtune=native -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -fstack-clash-protection -fcf-protection -flto=auto -MT main.o -MD -MP -MF .deps/main.Tpo -c -o main.o main.c
main.c:30:10: fatal error: rpc/types.h: No such file or directory
   30 | #include <rpc/types.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:261: main.o] Error 1
make[1]: Leaving directory '/tmp/makepkg/build/voiphopper/src/voiphopper-2.04/src'
```

I think `rpc/types.h` should now be taken from `/usr/include/tirpc/rpc/types.h`.

`gcc --version | head -n1`: `gcc (GCC) 13.2.1 20230801`  
on Artix GNU/Linux.

Regards!

---

[1] https://voiphopper.sourceforge.net/index.html
[2] https://sourceforge.net/projects/voiphopper/files/voiphopper-2.0/voiphopper-2.04.tar.gz/download

**Comment by iknowjason** [comment]
Thank you @dreirund 

I do need to review the version on sourceforge.  It has been many years.  It is just that Github has been more frequently used by professions in recent years.

Thanks again!

**Comment by dreirund** [comment]
On Sat, 13 Jan 2024 08:30:50 -0800, Jason Ostrom
***@***.***> wrote:

> I do need to review the version on sourceforge.  It has been many
> years.  It is just that Github has been more frequently used by
> professions in recent years.

So I am a bit confused; which then is your authorative repository?

**Comment by iknowjason** [comment]
Hello @dreirund please give me a chance to review and think about this.  I have not been maintaining VoIP Hopper for many years, as I said before.  But I'm happy to go back and fix this issue now that I'm aware.  From what I am seeing users are still downloading from Sourceforge.  So I need to look at that code, compare it to Github, and then see if I need to archive the one on Sourceforge and point everyone over to Github.

I need some time to review this and consider the pros and cons of the approach.  I would appreciate if you have a preference on Sourceforge versus Github, please do let me know.  Thanks.

**Comment by dreirund** [comment]
OK, thanks, now it is clear to me!

I do not have any preference of the one or the other.

**Comment by iknowjason** [comment]
@dreirund 

Are you aware that the Kali Linux team has been actively maintaining voiphopper?  I am thinking it might be a good idea to point the https://voiphopper.sf.net download page over to the Kali Linux package.  I tested their version to compile from src and it has the same error generated.  In ```main.c```, line 30, it shows rpc.h header file in the same location.  

https://gitlab.com/kalilinux/packages/voiphopper

**Comment by iknowjason** [comment]
@dreirund 

On Kali Linux, when I edit to make your suggested change, I get another error on ```netconfig.h``` header file.  So need to make sure we are suggesting the best resolution to this.  

```
└─$ grep types.h src/main.c
#include <tirpc/rpc/types.h>
#include <sys/types.h>
                                                                                                        
┌──(kali㉿kali)-[~/Downloads/testing/sf-voiphopper]
└─$ make
Making all in src
make[1]: Entering directory '/home/kali/Downloads/testing/sf-voiphopper/src'
gcc -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"voiphopper\" -DVERSION=\"2.04\" -I.     -g -O2 -MT main.o -MD -MP -MF .deps/main.Tpo -c -o main.o main.c
In file included from main.c:30:
/usr/include/tirpc/rpc/types.h:93:10: fatal error: netconfig.h: No such file or directory
   93 | #include <netconfig.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:261: main.o] Error 1
```

**Comment by iknowjason** [comment]
I'm also seeing their patches as well:

https://gitlab.com/kalilinux/packages/voiphopper/-/tree/kali/master/debian/patches?ref_type=heads

**Comment by iknowjason** [comment]
Hey @dreirund After looking this over, I've made the decision to archive this repository.  For the latest VoIP Hopper package that includes the fix you mention, please check out the Kali Linux maintainer page:

https://gitlab.com/kalilinux/packages/voiphopper

As for SourceForge, I have changed the download link pointing to the Kali Linux repository for voiphopper.
